from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdminCompletedTestsListView,
    AdminCompanyDetailView,
    AdminCompanyListView,
    AdminCreateRecommendationView,
    AdminDashboardView,
    AdminJobRecommendationDetailView,
    AdminJobRecommendationListView,
    AdminPersonalizedTestCreateView,
    AdminPersonalizedTestDetailView,
    AdminQuestionCategoryDetailView,
    AdminQuestionCategoryListView,
    AdminQuestionTemplateDetailView,
    AdminQuestionTemplateListView,
    AdminQuestionCreateView,
    AdminRecommendationsListView,
    AdminResourceCategoryDetailView,
    AdminResourceCategoryListView,
    AdminResourceDetailView,
    AdminResourceListView,
    AdminTestAnswersView,
    AdminTestAssignView,
    AdminTestByRequestView,
    AdminTestAddTemplatesView,
    AdminTestRequestListView,
    CurrentUserView,
    CustomTokenObtainPairView,
    StudentAnswerSubmitView,
    StudentDashboardView,
    StudentMyResourcesView,
    StudentRecommendationExportView,
    StudentRegistrationView,
    StudentRecommendationsView,
    StudentResourceDetailView,
    StudentResourceListView,
    StudentResourceProgressView,
    StudentTestDetailView,
    StudentTestListView,
    StudentTestRequestView,
    StudentTestSubmitView,
)


urlpatterns = [
    path('auth/register/', StudentRegistrationView.as_view(), name='student-register'),
    path('auth/token/', CustomTokenObtainPairView.as_view(), name='token-obtain'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('auth/me/', CurrentUserView.as_view(), name='current-user'),
    path('student/dashboard/', StudentDashboardView.as_view(), name='student-dashboard'),
    path('student/test-requests/', StudentTestRequestView.as_view(), name='student-test-requests'),
    path('student/tests/', StudentTestListView.as_view(), name='student-test-list'),
    path('student/tests/<int:test_id>/', StudentTestDetailView.as_view(), name='student-test-detail'),
    path('student/tests/<int:test_id>/answer/', StudentAnswerSubmitView.as_view(), name='student-submit-answer'),
    path('student/tests/<int:test_id>/submit/', StudentTestSubmitView.as_view(), name='student-submit-test'),
    path('student/recommendations/', StudentRecommendationsView.as_view(), name='student-recommendations'),
    path('student/recommendations/<int:recommendation_id>/export/', StudentRecommendationExportView.as_view(), name='student-export-recommendation'),
    path('student/resources/', StudentResourceListView.as_view(), name='student-resources'),
    path('student/resources/<int:pk>/', StudentResourceDetailView.as_view(), name='student-resource-detail'),
    path('student/resources/<int:resource_id>/progress/', StudentResourceProgressView.as_view(), name='student-resource-progress'),
    path('student/my-resources/', StudentMyResourcesView.as_view(), name='student-my-resources'),
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/test-requests/', AdminTestRequestListView.as_view(), name='admin-test-requests'),
    path('admin/test-requests/<int:request_id>/create-test/', AdminPersonalizedTestCreateView.as_view(), name='admin-create-test'),
    path('admin/test-requests/<int:request_id>/test/', AdminTestByRequestView.as_view(), name='admin-test-by-request'),
    path('admin/tests/<int:pk>/', AdminPersonalizedTestDetailView.as_view(), name='admin-test-detail'),
    path('admin/tests/<int:test_id>/questions/', AdminQuestionCreateView.as_view(), name='admin-create-question'),
    path('admin/tests/<int:test_id>/add-templates/', AdminTestAddTemplatesView.as_view(), name='admin-add-templates'),
    path('admin/tests/<int:test_id>/assign/', AdminTestAssignView.as_view(), name='admin-assign-test'),
    path('admin/tests/completed/', AdminCompletedTestsListView.as_view(), name='admin-completed-tests'),
    path('admin/tests/<int:test_id>/answers/', AdminTestAnswersView.as_view(), name='admin-test-answers'),
    path('admin/tests/<int:test_id>/recommendation/', AdminCreateRecommendationView.as_view(), name='admin-create-recommendation'),
    path('admin/recommendations/', AdminRecommendationsListView.as_view(), name='admin-recommendations'),
    path('admin/question-categories/', AdminQuestionCategoryListView.as_view(), name='admin-question-categories'),
    path('admin/question-categories/<int:pk>/', AdminQuestionCategoryDetailView.as_view(), name='admin-question-category-detail'),
    path('admin/question-templates/', AdminQuestionTemplateListView.as_view(), name='admin-question-templates'),
    path('admin/question-templates/<int:pk>/', AdminQuestionTemplateDetailView.as_view(), name='admin-question-template-detail'),
    path('admin/resource-categories/', AdminResourceCategoryListView.as_view(), name='admin-resource-categories'),
    path('admin/resource-categories/<int:pk>/', AdminResourceCategoryDetailView.as_view(), name='admin-resource-category-detail'),
    path('admin/resources/', AdminResourceListView.as_view(), name='admin-resources'),
    path('admin/resources/<int:pk>/', AdminResourceDetailView.as_view(), name='admin-resource-detail'),
    path('admin/companies/', AdminCompanyListView.as_view(), name='admin-companies'),
    path('admin/companies/<int:pk>/', AdminCompanyDetailView.as_view(), name='admin-company-detail'),
    path('admin/job-recommendations/', AdminJobRecommendationListView.as_view(), name='admin-job-recommendations'),
    path('admin/job-recommendations/<int:pk>/', AdminJobRecommendationDetailView.as_view(), name='admin-job-recommendation-detail'),
]

