# Generated by Django 5.2.8 on 2025-11-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('course', 'Course'), ('book', 'Book'), ('certification', 'Certification'), ('tool', 'Tool'), ('community', 'Community'), ('report', 'Report'), ('other', 'Other')], default='article', max_length=20)),
                ('url', models.URLField(blank=True, help_text='External link to the resource')),
                ('file', models.FileField(blank=True, help_text='Upload file if resource is downloadable', null=True, upload_to='resources/')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost if not free', max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('career_recommendation', models.ForeignKey(blank=True, help_text='Leave blank for general resources available to all careers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.careerrecommendation')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.resourcecategory')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Student's personal notes about this resource")),
                ('is_favorite', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.careerresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Resource Progress',
            },
        ),
        migrations.AddIndex(
            model_name='careerresource',
            index=models.Index(fields=['career_recommendation', 'is_active'], name='core_career_career__452d06_idx'),
        ),
        migrations.AddIndex(
            model_name='careerresource',
            index=models.Index(fields=['category', 'is_active'], name='core_career_categor_3998a4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresourceprogress',
            index=models.Index(fields=['student', 'status'], name='core_studen_student_44381e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentresourceprogress',
            unique_together={('student', 'resource')},
        ),
    ]
