# Generated by Django 5.2.8 on 2025-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questioncategory_questiontemplate_optiontemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='E.164 format recommended, e.g. +911234567890', max_length=20, null=True, unique=True),
        ),
    ]
