# Generated by Django 5.2.8 on 2025-12-07 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Company contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('description', models.TextField(blank=True, help_text='Company description/details')),
                ('location', models.CharField(blank=True, help_text='Company location', max_length=255)),
                ('industry', models.CharField(blank=True, help_text='Industry sector', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job position title', max_length=255)),
                ('job_description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements/qualifications')),
                ('salary_range', models.CharField(blank=True, help_text='Salary range if available', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=50)),
                ('application_url', models.URLField(blank=True, help_text='Link to apply for this position')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_recommendation', models.ForeignKey(help_text='Career recommendation this job is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='core.careerrecommendation')),
                ('company', models.ForeignKey(help_text='Company offering this position', on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='core.company')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['career_recommendation', 'is_active'], name='core_jobrec_career__d4456f_idx')],
            },
        ),
    ]
