# Generated by Django 5.2.8 on 2025-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_jobrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrecommendation',
            name='companies',
            field=models.TextField(blank=True, help_text='List of companies (one per line) that offer this career'),
        ),
    ]
